### ISSUE TITLE
SEB(Mac) vs Angular

### ISSUE THREAD

**Issue by pajda777** [SafeExamBrowser/seb-mac#1]
Hello,
we have our test module written in Angular. It works fine in SEB(Win) , however it doesn't run under SEB(Mac). We tested even simpler Angular 1.3 projects and it doesn't start either. We made sure that latest webkit is installed on the system...

We would appreciate any comments on that.

Thanks a lot!

**Comment by danschlet** [comment]
The current version of SEB for Mac OS X 2.1 has a known bug which appears on some systems, most likely when running on OS X 10.10 Yosemite: The browser user agent key is sometimes not being send. 

Did you use SEB on OS X 10.10? If not, is your test module working in Safari? And if so, is it working in all recent OS X versions in Safari or only on some specific ones?

Besides that, SEB has to use the old-fashioned WebView and not the new WKWebView, which is used by recent versions of Safari, but for apps it's only available starting OS X 10.10 (we need to support older versions of OS X too). WebViews are missing some newer HTML5 features which WKWebView and Safari offers. So if Angular is only compatible with recent Safari versions (released at the same time or later than OS X 10.10), then it would explain why it's not working with SEB.

**Comment by pajda777** [comment]
Hello,
Thanks for your answer...
our angular project works in all recent versions of OS X and Safari.
Can we prepare some special URL for you so you can at least see an error in log or something?

Thanks again

**Comment by danschlet** [comment]
Hi, yes, please send me (private message) a URL so I can test it. It's possible that there would be an error in the SEB log (also see section http://safeexambrowser.org/macosx/mac_usermanual_en.html#SecurityPane for where to find the log).

Is your project using IndexedDB? This is not supported directly in SEB (because WebView lacks support for it), but it can be emulated by using IndexedDBShim, which runs on WebSQL which is supported in SEB for macOS, see here for more details: 
https://sourceforge.net/p/seb/discussion/3704033/thread/11fe6e45/
