### ISSUE TITLE
No scroll bars in Mac OS Big Sur

### ISSUE THREAD

**Issue by npierson** [SafeExamBrowser/seb-mac#105]
Hello,

We have an issue where our exams have no scroll bars on systems running the latest Mac OS (Big Sur).  It is inconsistent, we have scroll bars on some pages, not on others.   

It is a serious issue since test-takers cannot scroll down some pages to see all the questions.    It has to do specifically with mouse scrolling, using the keyboard up and down arrows does work.

Has anyone heard about this or have suggestions?

A shaky phone video :
https://photos.app.goo.gl/HHBAzqVgu4cT2iEH7

**Comment by danschlet** [comment]
I'm not sure from your video what the expected behavior would be or how SEB behaves differently than other apps or browsers?

You know the macOS setting in System Preferences / General / Show scroll bars? I use the option "Always" because I guess I had similar issues with scrolling in other apps (and it makes sense to always see scroll bars because you know how much content the page has and which portion is visible in the window...). But I would have guessed that even with "Automatically based on mouse or trackpad" and "When scrolling" it should work, unless Apple messed up something in Big Sur (which wouldn't surprise me). Also I don't know if there are differences based on what kind of mouse you use and if that issue also happens when you use the two finger scroll on the trackpad on a MacBook.

<img width="780" alt="Screenshot 2021-07-27 at 12 21 47" src="https://user-images.githubusercontent.com/2464749/127139118-2f8e70c5-ab8f-4bde-81a6-9ff63ee0de95.png">

**Comment by npierson** [comment]
Thank you so much.  When I dig into the Mac OS Big Sur "General" settings and click on "Always" for Show scroll bars, it fixes the issue.

This extends beyond any quirk that I had with my mouse and system that this was tested on.  When Big Sur was released recently, we got a number of support tickets from students taking our exam who experienced this no scrollbar issue.   All were confirmed to be using Big Sur.

Since this issue only arose for us as Big Sur was being released, it certainly smells like a quirk of the release, that possibly if you had not set it for scrollbars showing all the time the behavior changed.

Thank you for your help.  We can offer this workaround to our students.

**Comment by danschlet** [comment]
Welcome, I'm happy this got solved. It's hard to keep track of all such changes Apple makes in OS releases, especially if you don't have to deal with a variety of devices which have different system settings than your personal device. I experienced this before as well...
