### ISSUE TITLE
Problem opening splash page for Mac users

### ISSUE THREAD

**Issue by BioKevin** [SafeExamBrowser/seb-mac#111]
Hello, have been using Safe Exam Browser a number of years as a high school teacher in the US.  Had my students download the latest version (3.3.0 for PCs, 2.3.2 for Mac users) and then had them download and run the config file that configures their client to send them to a splash page when they launch SEB (the splash page lets them out if they want to quit without a password but contains a link to another config file that sends them to my Moodle site and locks them down with a quit password and quit link options). 

It seems a number of my students have shown me the problem that when they launch SEB after running the client-configuring file on their Mac, it never successfully connects to the splash page (I don't see a wifi icon either ... is it possible that they're not connected to wifi for some reason after running SEB?) ... not able to confirm whether this is affecting literally all students using Macs or just some.  One student had an older version of OS X (I believe 10.14), but another student with the problem was running OS x 11.  None of my students on the PC side running SEB 3.3.0 have had any problem.

I am mostly reusing a config file from past years, though I did try to download the newest version on my own PC (3.3.0) and open the config file utility to look at the options.  Tried looking at features that were new to the Mac update but I didn't see anything relevant (to my untrained eye).  

Would be happy to attach that client-configuring seb file as well if that would help, but figured I would wait for you to confirm first.

Thank you for your product and service,
Kevin B
Atlanta, GA, USA

**Comment by danschlet** [comment]
You can display the macOS menu bar while using SEB, then students can reconnect to Wi-Fi using the menu bar item for it. Connections issues are not easy to remotely figure out, you will need to look at it yourself or ask some system administrators/supporters. 

Please note that SEB might not connect to https servers if students use anti-malware software which replaces root certificates to break https encryption (because the want to analyze network traffic, which is BS and shouldn't be used). [See our FAQ](https://safeexambrowser.org/faq/faq_en.html#Windows) for similar problems on Windows.

**Comment by danschlet** [comment]
If no further feedback received, this issue will be closed.
