### ISSUE TITLE
SEB ond IPad-Pro 5th Generation

### ISSUE THREAD

**Issue by dkummer63** [SafeExamBrowser/seb-mac#120]
I am responsible for SEB support at our high school. I have a student with an Ipad-Pro IOS 2th generation with systemversion 15: 
Modell: iPad Pro (12,9 Zoll, 2. Generation) 
Software: 15.0 (19A5307g)

When he tries to download the **SEB browser from the store**, the error message appears: The program does not run on this version.
What can I do?

**Comment by danschlet** [comment]
iOS 15 is still a beta version, SEB doesn‘t run on pre-release versions of iOS because of possible security issues (happened in the past). You can either add a setting to your configuration file to allow this SEB version to run on the iOS 15 beta (see its Settings / Security / Allow Running on iOS Beta / select iOS 15 or add the key allowiOSBetaVersionNumber with the value 15 to the config file manually).

In the next couple of weeks an update will be released which will run by default on iOS 15. The final version of iOS 15 will probably be released soon.

**Comment by dkummer63** [comment]
Thank you very much!
