### ISSUE TITLE
What causes "No Kiosk Mode Available"

### ISSUE THREAD

**Issue by xavier-bw** [SafeExamBrowser/seb-mac#122]
Hi,

A school reported receiving this message with one or 2 students every time they run a test on SEB/iPad.  

**No Kiosk Mode Available
Neither Automatic Assessment Configuration nor (Autonomous) Single App Mode are available on this device or activated in settings.  Ask your exam support for an eligible exam environment.  Sometimes also the restarting the device might help.**

Restarting the devices always helps, but of course it's an annoying disruption / loss of time.

Do you have any more information on what causes this problem?  Are there any settings on the iPad or in the SEB configuration that could be changed to prevent this?

Thanks,

Xavier

**Comment by danschlet** [comment]
Are you using the latest 3.0 version?

Usually this error is displayed after SEB (or another app which also uses the AAC single app mode) initially crashed while it already activated the AAC single app mode. Sometimes a crash isn't obvious, because it is immediately restarted (shortly the home screen is visible).

There is also an iOS issue which affects MDM managed iPads and apps which use the classic WebView (UIWebView). SEB 3.0 uses the classic WebView depending on the LMS/exam system and SEB settings. So if your iPads are managed and not private devices, this might be the reason.

You could try to send us the log file, either if you scroll down in the About SEB window or use the option in the iOS Settings app in the SEB section.

**Comment by xavier-bw** [comment]
Thanks, I've passed your feedback and questions to the school that encountered the issue.  When I get more information I'll pass it on.
