### ISSUE TITLE
seb:// and sebs:// protocols crash on SEB 3.0.1 iOS

### ISSUE THREAD

**Issue by t00** [SafeExamBrowser/seb-mac#134]
After upgrading to iOS 15 and SEB to 3.0.1, both seb and sebs protocols are causing SEB to crash when starting. No request is being made to the server to download the seb configuration file.

After clicking (any browser - tried Safari and Firefox which nicely shows the actual link clicked), a white SEB background is shown for 1 second and closes afterwards.

To reproduce use [a simple jsfiddle](https://jsfiddle.net/9nhzqw34/)

**Comment by danschlet** [comment]
SEB 3.0.1 on iOS 15 works perfectly fine will all my testing links on the pages below and in Moodle >= 3.9 with the Lauch SEB button.

When I try to open the links from the jsfiddle (which doesn't work at all from Safari, nothing happens when clicking those links, it only worked in Firefox), then SEB displays the error below. Either your settings are somehow wrong formatted (wrong plist header, some other wrong formatting) or SEB cannot download them, maybe because of authentication.

Did you try the exact same configuration file with SEB 3.0 on iOS 14? For me it doesn't work with SEB 3.0.1 on iOS 14.8 neither.
![IMG_0042](https://user-images.githubusercontent.com/2464749/134467126-9bb43859-958f-48ba-8fc2-38f081cef4d5.PNG)

**Comment by danschlet** [comment]
You have to provide real settings and not a fake seb(s) link...

If you configure SEB client settings to show some page without a quit password, the error message below would be displayed. The error is currently not displayed when SEB is started with a seb(s) link or when opening a .seb file. I will improve that error message and displaying sometimes, but that wasn't changed at least since SEB 3.0 (it might have worked better in SEB 2.x, but 3.0 was a major refactoring and there surely still are some flaws).

**Comment by t00** [comment]
Thank you for taking time to answer and re-check the issue. I just finished testing it with a colleague on 2 devices - iPhone 11 with iOS 14.8 and iPad mini 5th gen with iOS 15 and the crash is always reproducible on the iPad mini. Both devices are running SEB 3.0.1.

Steps to reproduce are slightly convoluted as SEB must be removed from memory for a crash to happen, one of 2 options:
 1. home -> swipe up SEB window
 2. uninstall SEB -> install SEB - do not open

The crash does not happen when SEB is opened prior to clicking on a link.

Now, I cannot be certain if this issue had existed on SEB 3.0.0 as well or earlier versions, or if it is related to iOS 15 but above should hopefully provide enough clues to reproduce it.

**Comment by danschlet** [comment]
I was able to reproduce the crash, as you mentioned when SEB is not running prior to clicking the link. Thanks for the report, I will add this issue to the backlog and fix it in the next update. 

I just want to make sure that this doesn't happen with a valid seb(s) link to a valid configuration file. If you would observe such a case, then please try to provide a reproducible test for that as well.
