### ISSUE TITLE
Quit Link Restarts Session

### ISSUE THREAD

**Issue by keean** [SafeExamBrowser/seb-mac#14]
When navigating to the Quit-Link on SEB for iOS, SEB exits SAM correctly, however, instead of returning to the iPad home page (quitting SEB), it "Restarts Session" by returning to the start page, and then confirming self lock. People taking the exams find this un-intuitive and end up going round in circles unable to quit (which requires you to press the home button between when it unlocks and when it locks again. Am I missing something obvious in the configuration, or is this how its supposed to work?

**Comment by danschlet** [comment]
**iOS apps don't "quit" themselves.** If you find an app which does that, then it doesn't follow Apple's guidelines. We are striving to strictly follow the usability standards of each plattform SEB is running on, even if this means that SEB versions don't behave in the same way on different operating systems.
But I see that users can be confused by the "Restart Session" dialog which is displayed after unlocking the device, I will change the behavior of SEB for iOS in this particular case to make it more clear that the exam was finished and the user can just return to the home screen.
You can avoid these misunderstandings by configuring SEB to display an exam portal/landing page first and put a link to the actual exam (or exam system) on that page. Just don't set any quit password in the client configuration of SEB which displays this landing page. Then place a seb(s):// link to a .seb config file saved for "starting an exam" onto this page. In these settings use a quit password. Then SEB locks the device only after the user taps this exam link and after submitting the exam and invoking the quit link, SEB will display this landing page again. This is the recommended way how to use SEB anyways (see the tutorial and this video for some possible ways how to configure and start exams on SEB for iOS).
Another advantage of this way to start exams with SEB is that you can easily change the quit password or other exam settings, because you don't need to change and deploy the configuration to all your exam clients. You just change the settings saved in the .seb file referenced by the seb(s):// link on your portal page and saved on your server.

**Comment by keean** [comment]
A landing page is a bit old-fashioned, the exam is a single page app, do you have any ideas how this can be done from JavaScript?
