### ISSUE TITLE
WebRTC challenges with specific exam systems/LMS

### ISSUE THREAD

**Issue by SebastianZiegler** [SafeExamBrowser/seb-mac#177]
Hello,

we use SEB with moodle for using the WebRTC feature its recommended to use the option "browserWindowWebView". So I created a Template for our moodle 3.9 with this option. 
When I enter SEB an our BBB open in a new SEB Tab, there no microphone or Webcam available.

Any ideas?

Best regards
Sebastian

**Comment by danschlet** [comment]
For Moodle to be fully compatible with SEB when using the modern WebView (where WebRTC works), this update of the Safe Exam Browser integration is necessary: https://tracker.moodle.org/plugins/servlet/mobile#issue/MDL-72188.
It will most likely be released with Moodle 4.0 soon.
Until then WebRTC could be used with a solution which opens a separate browser window and uses a different host URL than the Moodle server, because SEB then uses the modern WebView for the additional window even with standard settings.

**Comment by SebastianZiegler** [comment]
Okay, the problem seems to be the Link.

I just linked the moodle bbb activity, then it doesn't work. If I link directly to an existing BBB-Meeting URL, it workes. So maybe the problem is the redirection when opening an BBB through moodle, because the window opens with the same host URL.

**Comment by danschlet** [comment]
Yes, for the "compatibility mode" I had to introduce some distinction about in which window SEB can use the modern WebView and where the classic needs to be used in which the Config Key HTTP request header check works. I added the criteria of the different host, as some exam systems can open several windows (I guess Moodle usually not) and would check the request headers in all of them.

**Comment by SebastianZiegler** [comment]
I can open new windows via link with moodle, the problem with the BBB activity is, that as the window opens we are still one the same host URL and then there will be a redirect to BBB.

**Comment by danschlet** [comment]
Yeah, that won't work, as SEB has to decide which WebView type to use at the moment when the window is opening. The only workaround that comes to my mind would be if you could open yet another window in BBB and use that one for proctoring.

When the updated Moodle-SEB integration is finalized, I guess it will be possible to install it as a plugin also in older Moodle versions than 4.0. There is one small issue which still needs to be fixed, otherwise it already works.

**Comment by danschlet** [comment]
Closed as this is a web application issue.
