### ISSUE TITLE
Camera access denied on MacOS/iPadOS

### ISSUE THREAD

**Issue by Rustam-Z** [SafeExamBrowser/seb-mac#180]
I cannot enter a test on MacOS 11.6, because it asks to grant access to camera, and there is no pop-up to press "Allow". Then I have tried to connect to test using iPad OS version 14.8, this time I could grant access to camera (while using QR reader), but still it shows the same error ("You can't start this Test as web-cam access has been denied or the web-cam isn't installed"). What should I do to enter the test?

**Comment by danschlet** [comment]
Probably your web application isn't compatible with SEB 3.x for Mac/iOS. If it has built-in support for SEB, this needs to be updated to work with the modern WebView, see [release notes](url) and our [developer documentation](https://safeexambrowser.org/developer/seb-config-key.html) (instead of the HTTP request header check, the SEB JavaScript API needs to be supported).

As this is an issue which needs to be fixed in the web application (assessment system or LMS), I'll close this issue. If you are a student/examinee, please let your exam provider know that they may have to update their SEB support for SEB Mac/iOS to be able to use the camera.

**Comment by Rustam-Z** [comment]
@danschlet Thanks Daniel, I'm also assuming the issue is with the web application. I will roll back to previous releases.
