### ISSUE TITLE
MacOS Big Sur freezing in lockdown browser: SEB 3.0

### ISSUE THREAD

**Issue by whitejg** [SafeExamBrowser/seb-mac#185]
I've seen freezing on Macs appears to be a general an issue. Your guide to unfreezing is great on the FAQ for Macs, I'm just looking into a possible fix or a way to limit the chances of it happening further.

I'm using your software for a course - having the students install the software then run a configuration file I supply to configure the browser. It's going very well with one exception. Some of my students occasionally have the browser freeze up on them when they use it. So far I've had about 100 students set their laptops up between two courses and I've had about a dozen students have the issue. So far, all are running MacOS Big Sur - however, I'd also bet the majority of my students who have Macs are running Big Sur - so may not be relevant, but it's what I've got so far.

The freezing appears to happen largely when either booting up or quitting SEB, but a few have it occur when navigating between the few pages they need to open the exam. It seems to be periodic for those individuals as well. Once clearing SEB, which occasionally has required restarting in safe mode, it doesn't necessarily happen again - but can. In the end, I have a two main questions: 

1. Would giving them a configuration file that only allows Big Sur and Monterey possibly help? As I've heard there are some significant differences between those two newer MacOSs compared to the older ones. I just doubt that by changing that setting it's going to dramatically limit what SEB is actually doing in the background.
2. Any ideas what might be causing the issue? Be that user error or a software issue. Any advice or recommendations would be greatly appreciated.

Thanks!

**Comment by danschlet** [comment]
SEB 3.0 has some known issues, the upcoming 3.1 release will surely run more stable. Unfortunately the classic WebKit web browser engine (which is part of the macOS version used) also crashes randomly (maybe depending on specific web content). It is possible that these browser engine related crashes got more common on Big Sur and Monterey, as Apple doesn't develop the classic WebView anymore. Depending on the LMS or exam system you're using, SEB might be forced to use the classic WebView instead of the modern WebKit browser engine, which is much more stable and has better compatibility to modern web content. The SEB integration in Moodle 4.0 for example will be updated, so SEB for Mac and iOS can use the modern WebView.

To find out more about the issues you mention we would need much more and very detailed information, see https://safeexambrowser.org/support_en.html for how to submit a proper issue report.

**Comment by danschlet** [comment]
Closed for lack of feedback.
