### ISSUE TITLE
Can Use Second Chrome Window with Multiple Monitors

### ISSUE THREAD

**Issue by arichbell** [SafeExamBrowser/seb-mac#22]
Hi there,

First of all, your work/project is AWESOME!! Thank you!!

We are currently integrating SEB into our LMS.  I have noticed that when I have 2 external monitors hooked up when I am opening an .seb file (and one of the monitors has another Chrome window open with multiple tabs); I am able to still go to each tab and scroll up/down while SEB has "locked down" the whole screen.  This seems like an edge case but I thought I'd let you know.  Is there a way the stop the user from interacting with that second window (not scroll up/down or go to another tab)?   Ideally, all other Chrome windows would close or SEB would refuse to open until all windows have been closed.  I am on OSX 10.12.6 (macbook pro mid 2015, 15 inch, 2.2 GHz i7, 16GB RAM, Intel Iris Pro 1536 MB)

Thank you

**Comment by danschlet** [comment]
Hi,

Thanks for your bug report. I could reproduce the issue, it happens when the window of another application is displayed in full screen = on another space on another monitor and SEB is started by opening a SEB config file. If starting the SEB application directly or using a seb(s):// link to a config, SEB correctly hides the app on the other space. The other app isn't fully accessible though, as SEB takes input focus back if someone clicks into the window of the other app, but as you mentioned it's possible to scroll through the open tabs and switch tabs. Unfortunately there is no API method to hide apps which run on another space, which makes handling this case a bit tricky. I will nevertheless fix that the app isn't hidden when starting SEB by opening the config file directly.

**Comment by danschlet** [comment]
This issue is less often happening in SEB 2.1.3. The final fix for all cases will be available in the next SEB for macOS version, as there will be a new setting to quit all running applications. This will increase security in BYOD exams generally, not only regarding this issue.
