### ISSUE TITLE
SEB Error

### ISSUE THREAD

**Issue by alphenox** [SafeExamBrowser/seb-mac#268]
I am locked out of my iPad and i cannot press quit. It just says Permissions Require for Web Application. Every time i press settings it just pops-up the same message. Please help

**Comment by danschlet** [comment]
I can't really reproduce your issue, which iOS version are you using and what kind of iPad model (with home button or Face ID, what model)?

Does SEB not switch to the Settings app when you tap the Settings button in the alert? There also should be a Cancel button in the alert, you can also tap that to quit that exam session. In the Settings app in the SEB section (scroll down or search for SEB there) you can then enable Microphone and Camera in the top section "Allow SEB to Access". Then the permissions dialog won't be displayed anymore.

In case your exam doesn't require camera and microphone access, then tell your exam provider to change SEB settings, because settings generated with a previous SEB version might cause the permissions dialog to be displayed in SEB 3.2.2 even though it isn't required for that particular exam.

If you're completely locked in SEB, you can still [force restart your iPad](https://support.apple.com/guide/ipad/force-restart-ipad-ipad9955c007/ipados).

**Comment by danschlet** [comment]
Closed due to lack of feedback.
