### ISSUE TITLE
SEB with iPad does not work 

### ISSUE THREAD

**Issue by Vilenova** [SafeExamBrowser/seb-mac#269]
I wanted to try out if I could do an English Voci exam with the Safe Exam Browser. To do this, I created a session with SEB for a self-test with an existing question set. I then installed SEB on an iPad and scanned the QR code of the session from SEB. The iPad then wanted to download an SEB file.

So far everything is okay. After the download, however, nothing happens, the screen remains gray and nothing can be done. I did not find the SEB file anywhere on the Pad.

iPad with iOS 16.2, SEB reinstalled.

And I never recieved the confirmation file, since everything was grey. 
I deinstalled and installed the app now three times, nothing changed..

**Comment by danschlet** [comment]
Maybe the configuration file you were given is not working. Ask them if they are sure it works with the current version of SEB for iOS. Also network issues could cause connection problems or when using some software/hardware firewall, proxy or VPN which manipulates the SSL certificates.

If you can provide us with a test login, we can try to reproduce the issue. Otherwise you have to ask the exam provider to contact us, so we can get a test access to debug an issue.

**Comment by Vilenova** [comment]
Hi, 

Thank you for the response. I can gladly ask the test provider for a test account for you. Which email address may he use for the access for you?

**Comment by Vilenova** [comment]
I can give you the email from the test provider if this would help?

**Comment by danschlet** [comment]
They can send us an email to info at safeexambrowser.org.
