### ISSUE TITLE
SEB Mac  copy paste is not working in WYSIWYG HTML editor

### ISSUE THREAD

**Issue by Royvarghe** [SafeExamBrowser/seb-mac#313]
In the SEB mac right click is not working in rich text editor. We tried the same in textarea, formula editor but its working, allow to paste the content (by right clicking and selecting the paste from the pop up). In rich text editor right click is doesnot bring up the pop up.

**Comment by danschlet** [comment]
The context menu is deactivated in SEB's browser, because it contains options which cannot be used in exams (could be used to cheat). We will look into if and how the context menu could be implented in a safe way (ommiting those not wanted menu options).

On Mac you can just use key shortcuts. I assume every Mac user would know that cmd-v is paste, cmd-c copy. Or does the formula editor implement its own copy-paste and key shortcuts don't work?
