### ISSUE TITLE
Audio auto pausing on click in iframe SEB on ipad

### ISSUE THREAD

**Issue by ray1618** [SafeExamBrowser/seb-mac#32]
When using the [plyr](https://github.com/sampotts/plyr) library for audio / video playback. The audio playback will be paused when clicking (tapping) anywhere on the screen. It only seems to happen when running in a iframe.
Also, it doesn't happen when running on IOS safari v11 & v12.

Is there a way to debug the content inside SEB?

**Comment by danschlet** [comment]
Currently web content can only be debugged inside SEB using Xcode (and by building the source code yourself), see the instructions and suggestions on [this Stack Overflow page](https://stackoverflow.com/questions/2767902/what-are-some-methods-to-debug-javascript-inside-of-a-uiwebview).

We might have a look of how to build in some web debugging framework, but this will have to wait, currently we have other priorities and not enough developer resources.

You can have a look at the log files SEB 2.1.3 for iOS saves (currently only available as [TestFlight beta](https://github.com/SafeExamBrowser/seb-testing/tree/master/ios)), but there is not much web logging in those logs.

The current SEB iOS/macOS versions use the older WebKit 1 (UIWebView/WebView) frameworks. We will support WebKit 2 (WKWebView), which is used by Safari, in SEB 3.0. But that version probably won't be available before Q3/Q4 2019.

When I tried to play the demo video on the plyr GitHub page (are they kidding showing ads before the video?), SEB was regularly crashing, especially when switching off full screen. I don't think that player is really compatible with UIWebView.

I didn't observe any audio pausing, do you have a link where I could test it with that content you used?

**Comment by danschlet** [comment]
Building SEB for iOS (at least for running on a real device instead of the Simulator) isn't as easy, the code signing identities need to be changed to yours and the provisioning settings changed, as I have a special provisioning profile which can activate the AAC single app mode (that only assessment developers can get from Apple).

Unfortunately I couldn't find any hints about why the audio stops when tapping anywhere into the web browser view. The web delegate methods don't get called when tapping. It looks like that happens inside of UIWebView, that means that I can't influence it.

I guess only WKWebView will solve the problem, which will be optionally supported in SEB around Q3 2019.

**Comment by ray1618** [comment]
To bad building / running the IOS code won't be easy.
Bu thanks for checking the audio problem. We will look for an workaround for now, and hope for the best when the WKWebView will be updated ;).

**Comment by danschlet** [comment]
WKWebView is available from SEB 3.0 for iOS/macOS (and improved in the upcoming final release of SEB 3.1).
