### ISSUE TITLE
System security feature is disabled" SEB is Locked

### ISSUE THREAD

**Issue by acgvar** [SafeExamBrowser/seb-mac#323]
After clicking "Launch Safe Exam Browser", the following error appears:
The Safe Exam Browser keys could not be validated. Check that you're using Safe Exam Browser with the correct configuration file.

After closing, SEB was launched again, but a red screen appears with the following error:
"System security feature is disabled"

Latest SEB software: SafeExamBrowser-3.3.dmg
MacOS Monterey 12.3.1

**Comment by acgvar** [comment]
Further investigation was conducted. Tried setting the "Allowed browser exam keys" to blank and reinstalled SEB. After doing this, the SEB runs smoothly. However, I think it is necessary to set "Allowed browser exam keys".

**Comment by danschlet** [comment]
Did that happen on a student device?

I assume there were two different SEB versions used, probably first one of the pre-release versions 3.3rc (release candidate), as there were bugs which caused the "System security feature is disabled" lock screen to be displayed. If you later reinstalled the final release version SEB 3.3, then you need to update the Browser Exam Key BEK in (Moodle's) "Allowed browser exam keys" quiz setting, as now every macOS SEB version (even if only the build version is changed) has a different BEK.

**Comment by acgvar** [comment]
Thank you. Both used the final release versions. The final release version SEB 3.3 was reinstalled, and its BEK was updated to the BEK listed in the quiz setting. The issue was still there but it is fine for now. As a temporary solution, we decided to set "Use an existing template".

**Comment by danschlet** [comment]
I would recommend to use SEB Verificator if something like this happens on a student device. If there are several versions of SEB on a Mac, it's not always predictable which one will get opened with a sebs:// link (like it's used in Moodle for starting a quiz in SEB) or even with opening a .seb file. I would always remove all other SEB versions. Especially check with SEB Verificator for an invalid SEB version if the BEK doesn't work, because that would indicate cheating or some malware which manipulated the SEB application.

**Comment by danschlet** [comment]
For an istance of wrong BrowserExamKeys, see issue https://github.com/SafeExamBrowser/seb-mac/issues/329.
