### ISSUE TITLE
Split View on iPad not blocked

### ISSUE THREAD

**Issue by schenni86** [SafeExamBrowser/seb-mac#399]
Error Description: The students have opened the test in the Safe Exam Browser. Switching to other apps is not possible. However, it is possible to use "Split View," which means dividing the screen via the three dots at the top of the screen (in the middle). Then, one can open any apps and use them alongside the Safe Exam Browser on the second half of the screen. 

Please modify the app accordingly so that the possibility of Split View is disabled.

iOS 17.4.1
SEB Version 3.3.3 (15180)

![WhatsApp Image 2024-05-03 at 11 02 01](https://github.com/SafeExamBrowser/seb-mac/assets/168827913/20a1e1ba-c3b9-4229-9bbd-95e24dab6a56)

**Comment by danschlet** [comment]
Did you set a **quit password** in your exam settings? In the iOS version this **must** be done, otherwise SEB is not running in secure mode (not activating the AAC Assessment Mode). 

You wrote "Switching to other apps is not possible", which would actually mean that SEB is running in secure mode, but I just tested it, Split View and Slide Over get disabled for me when using iPadOS 14.7.1 and SEB 3.3.3. Maybe you got confused using different SEB settings?

Btw., SEB doesn't deactivate single features like Split View, on iOS almost all system features are deactivated by this iOS built-in single app mode called Automatic Assessment Configuration (AAC) or Assessment Mode. So in case some system features suddenly work in this mode, it's with highest probability an iOS/iPadOS bug (and there have been several especially since iOS 17 was released).

**Comment by schenni86** [comment]
Thanks for the immediate response. No, I didn't set a passwort for finishing the exams. This was my first way to avoid students being able to open other apps, but our moodle admin found another way to block this. Anyhow, her solution doesn't block the split view, so I'll just set a quit passwort and then it should be finde :-D.
