### ISSUE TITLE
Full screen problem

### ISSUE THREAD

**Issue by eggib** [SafeExamBrowser/seb-mac#4]
SEB 2.1.2 for mac, Mac 10.10.5 **Yosemite**
When using SEB with https://geogebra.org/exam buttons and checkboxes on the web page are inactive (or at least not clickable). 
The page geogebra.org/exam is in html5 full screen mode.
Using the same URL without SEB everthing is working.
Using Mac 10.9 or Mac 10.11 everthing is working.

![img_4134](https://cloud.githubusercontent.com/assets/19183471/25953151/cec3cc06-3662-11e7-9f39-b69b1f0aecf3.jpg)

**Comment by danschlet** [comment]
WebKit on OS X 10.10 has a lot of bugs. I'm currently investigating if there is a way of preventing such issues. Safari uses usually a newer WebKit version than the one provided by Mac OS, which SEB has to use currently.

**Comment by danschlet** [comment]
I investigated the problem and couldn't figure out yet why it happens. As there are no errors in the SEB log and no exceptions in syslog, this is very hard to debug (I also cannot run SEB on OS X 10.10 in Xcode's debugger).

Maybe the HTML5 full screen command causes the issue, as that isn't supported by the WebView SEB uses for its browser windows (Safari on 10.10 supports it). I will try if can block it.

Tell everybody to update 10.10 Yosemite to a proper macOS. 10.10 really has the worst WebKit version ever. 

I will once again try to compile my own WebKit instance and embed in future SEB versions, but I doubt that current WebKit versions still can be run on OS X 10.10, as this isn't supported anymore by Apple since 10.13 was released (Apple only supports and updates the 3 latest major macOS versions).
