### ISSUE TITLE
How to use seb on ipados 13?

### ISSUE THREAD

**Issue by 18gatenmaker** [SafeExamBrowser/seb-mac#40]
Because seb says no to my ipad

**Comment by danschlet** [comment]
It says no to your iPad because you are using a beta version of iOS. iOS Beta versions are not final and the single app mode might have bugs which would allow to cheat or SEB might not run stable on the beta. That's why SEB doesn't run on major beta versions unless the exam organizer allows it with a special setting. When the final version of iOS 13 is released, it will run on SEB (updated version 2.1.15 which will be released soon).

In the current version, the setting "Allow running on iOS Beta" needs to be set to "iOS 13", see [Settings / Security](https://safeexambrowser.org/ios/ios_usermanual_en.html#SecurityPane) / Allow running on iOS Beta.
