### ISSUE TITLE
Getting different Configkeyhash for IOS for same seb configuration.

### ISSUE THREAD

**Issue by VarunTwri** [SafeExamBrowser/seb-mac#421]
**Describe the bug**
Using latest approach of getting config key hash and browser key hash with SEB API.
Getting different Configkeyhash for IOS for same seb configuration.

**To Reproduce**
-Open same configuration in different device and check respective config keys.

**Expected behavior**
ConfigKeyHash should be same for all devices.

**Screenshots**
Macos
![image](https://github.com/SafeExamBrowser/seb-mac/assets/102298041/316b39f5-5fe6-4573-a64d-08b2e308e143)

Windows
![image](https://github.com/SafeExamBrowser/seb-mac/assets/102298041/ade237b0-9334-4e57-a4da-c7e384d41790)

IOS:
![image](https://github.com/SafeExamBrowser/seb-mac/assets/102298041/7355763d-652c-4590-bb15-aa40432585fc)

**Version Information**
Please complete the following information: 
 - OS: IOS 17.5.1
 - SEB Version mac OS 3.3.3 , iOS 3.3.3, win 3.7

**Comment by danschlet** [comment]
I can't reproduce any issues with SEB for iOS and the ConfigKey. Try the Moodle quizzes linked on the page https://safeexambrowser.org/exams. They work both on Mac and iOS 3.3.3.

Are you sure that your website doesn't have another URL on a mobile device (for example https://m.server.com instead of https://server.com)? The hash which can read through the SEB Javascript API are hashed with the URL of the page. Therefore the URL must be same to be able to compare the ConfigKeys. You probably should print the URL as well on your test page.
