### ISSUE TITLE
Settings or Config files are overwritten by MDM, even when no plist is configured in the MDM

### ISSUE THREAD

**Issue by seangirard** [SafeExamBrowser/seb-mac#43]
First off... SEB is awesome and I am not sure this is an SEB issue, specifically. But it does impact SEB and at the very least may need to be documented or better understood.

The following applies to iOS devices managed via MDM (we use JAMF, not sure if this is specific to JAMF or MDMs in general). We don't manage non iOS devices via MDM, so I'm not sure if there are implications for OSX or Windows.

What we have found is that iPads managed via JAMF always default to the MDM-supplied config, even when no plist is configured in the MDM (in that case it always launches to "enter a url" start screen, like when you first install SEB).

What this means is that .seb files set to act as permanent config files are never stored as a permanent config. The will work normally when they are first "opened" as long as the config is in memory, but once SEB is quit, it always reverts back to the "blank config". This issue does not occur if the device is not managed via MDM.

If you open a .seb file configured to start an exam, you briefly see the "enter password" screen, but then it is replaced with the "enter a url" start screen. Effectively you have click/open the settings file twice: once to "launch SEB" to the default state and a second time to use the settings file.

We are working around this now by just using the MDM to deliver a configuration and then using a "portal" page.  But this is new, and I am fairly certain, unintended behavior. I don't know if the underling issue is with iOS, MDMs (generally), JAMF (specifically), or SEB. Or it's just an edge case of the specific interaction of all 3.

I'm happy to provide more detail or perform what testing I can. Thanks!

**Comment by danschlet** [comment]
Thanks for the report. I actually also observed a strange behavior of the MDM Managed (App) Configuration feature. On a managed iOS device with a MDM-supplied config, it is delivered all the time while SEB is running. I worked around that by just applying it once, unless it changes. I also observed that the MDM-supplied config continues being delivered to SEB, even if I remove the "App Configuration" payload in the MDM. I think this is the same issue you're observing. If an empty config is delivered in this way to SEB, it will use its hardcoded default settings, which results in the "Initial Configuration Assistant" view (with the "Enter a URL" etc options) being displayed. I was testing with Apple's macOS Profile Manager, so I guess it's not a JAMF issue.

Did you test it with iOS 13? I observed the issue with iOS 12, didn't test it with iOS 13 yet.

I think this is an iOS bug, but I will investigate further. Maybe I can fix it in SEB or at least implement a workaround.

I think as a workaround in the current SEB version, you could apply a client configuration on your devices where you just enter some SEB administrator password. Then when the empty config is delivered by MDM, SEB won't be reconfigured, as the SEB administrator passwords must match in the current and new client config. Like that you would still get the "Initial Configuration Assistant" view displayed like if you freshly install SEB.

**Comment by seangirard** [comment]
Thanks @danschlet I have tested and confirmed this on both iOS 12 and 13. I think in my early investigation on this I did land on the workaround you suggest (or that sequence of steps anyway) and it was still overwritten, but I will try to confirm that for sure and report back.

**Comment by danschlet** [comment]
In the final beta (release candidate) build of SEB 2.1.16, I made big changes in when and how MDM App Configuration is applied. I'm quite positive that this issue won't happen anymore, even though I currently cannot test it thoroughly (Corona's fault). It would be great if you could test it with the beta (do you have TestFlight access already? Otherwise please send me an e-mail to info at safeexambrowser.org).

In my tests a few weeks ago with Jamf Pro, when I removed the app configuration dictionary, there was no empty config being sent to the devices anymore. But you really need to remove the app configuration (I guess the "payload"). If you delete the deployed SEB version and install it from the App Store, the payload is still being sent by the MDM and applied in SEB. That's weird, because I thought having read that Managed App Configuration only works when the app was deployed by MDM (it looks like they should clarify "when the app initially was deployed by MDM).

**Comment by danschlet** [comment]
Closed as now further feedback was provided. Issue most likely fixed with SEB for iOS 2.1.16.
