### ISSUE TITLE
SEB not working , not running on iOS 18

### ISSUE THREAD

**Issue by mghaly6** [SafeExamBrowser/seb-mac#435]
Hello there,

We have encountered an issue with the safe exam browser error on iPads following the update to iOS 18.0. The error message states "Running on New iOS Version Not Allowed."

We would greatly appreciate your feedback and suggestions on this matter.

Thank you!

![20240917_102934](https://github.com/user-attachments/assets/db7d64e1-926a-4f47-904c-d5717ef72d93)

**Comment by peha2407** [comment]
Same problem here. Thank you!

**Comment by danschlet** [comment]
See instructions here https://github.com/SafeExamBrowser/seb-mac/issues/416.

The new version 3.4 which is compatible with iOS 18 is on the way.

**Comment by robinpaimanto** [comment]
Hello.  Thanks to @danschlet .
I have tried and works very well on iOS 18.0

For Administrator :
1.  Open setting > input administrator password
2. Security > IOS > Allow running on iOS beta > Type : 18
3. Configuration > Save Setting As
4. Upload "configuration file" to your website. in my case, upload to website folder : agendasekolah.id/safeexambrowser (https://safeexambrowser.org/developer/seb-automatic-client-configuration.html)

For Student :
1. Uninstall SEB
2. Download SEB from Appstore (Do not open SEB)
3. Ipad Home > Setting > Apps > SEB > "Allow Editing : Check" dan "Initiate Settings Reset : Check"
4. Open SEB > type website name / Scan QR

And also I have the video on Youtube : https://youtu.be/gO1p3c-9cWc

**Comment by mghaly6** [comment]
Thanks @robinpaimanto for the video appreciate it work @danschlet thanks for your support we will wait until new version

**Comment by Fhfueuizuz** [comment]
hello i accidentally logged in with the same code as that man and can't get out, what is de code to get out of safe exam browser. 
![IMG_6025](https://github.com/user-attachments/assets/412340e5-9212-4fac-9f7d-50373edd1fd8)

**Comment by danschlet** [comment]
We don't know and we don't set any passwords in SEB. The ones who set up that exam know the password they used.

**Comment by sertorvalentinus** [comment]
both solutions not working, after i downloaded seb from testflight it cant open and keeps crashing, any solutions ? ^-^

**Comment by eagles1227** [comment]
@danschlet 

Haven’t seen any updates on the app store, do you know when the update is coming??

**Comment by danschlet** [comment]
I hope the App Store review happens today, it was delayed.

**Comment by mghaly6** [comment]
Hello @danschlet,   I wanted to thank you for releasing version 3.4 two hours ago. I tested it and it is working perfectly fine. I did notice that it has not been updated in the Download Latest Releases section yet. Thank you for your hard work and dedication to keeping everything running smoothly.   
<img width="1200" alt="Screen Shot 2024-10-01 at 2 54 30 PM" src="https://github.com/user-attachments/assets/18df16ca-d4b9-4f46-a1ec-0138132dd42a">

**Comment by eliassfeir1** [comment]
Dear Support,

When we updated the SEB to 3.4 to support the IOS 18 on the iPads, a new issue started to happen.
Whenever we launch the SEB through Moodle, a pop up message displays the following: "Loading New SEB Settings Not Allowed!"

This issue is happening on IOS 16, 17 and 18.

https://github.com/user-attachments/assets/7fe2cca7-461d-40f7-a88a-2a4936427128

**Comment by danschlet** [comment]
Which Moodle version are you using?

From SEB 3.4 onwards you need the new version of the SEB Moodle integration, which is available built-in in Moodle 4.1 and newer (I think also in some latest 4.0.x versions). It can also be updated in older Moodle versions.

Didn't you get the overlay notification on the top of the screen in SEB when loading the first Moodle page which explains that a Moodle integration or settings need to be updated to be compatible with the modern WebView?

**Comment by lin-beta8** [comment]
> Dear Support,
> 
> When we updated the SEB to 3.4 to support the IOS 18 on the iPads, a new issue started to happen. Whenever we launch the SEB through Moodle, a pop up message displays the following: "Loading New SEB Settings Not Allowed!"
> 
> This issue is happening on IOS 16, 17 and 18.
> 
>  SEB-Issue.mp4

Hiiii, the same thing happens to me, i dont know what to do.

**Comment by danschlet** [comment]
Same question to you: **Which Moodle version are you using?**

To all of you, please send us your log files. On iOS, go to iOS Settings, find SEB (in iOS 18 in sub-menu "Apps"), select "Initiate Sending Logs" and return/start SEB. Best is to mail the log file to yourself and then attach it here.

**Comment by lin-beta8** [comment]
> Same question to you: **Which Moodle version are you using?**
> 
> To all of you, please send us your log files. On iOS, go to iOS Settings, find SEB (in iOS 18 in sub-menu "Apps"), select "Initiate Sending Logs" and return/start SEB. Best is to mail the log file to yourself and then attach it here.

the moodle version is 4.4.1 and I can’t send log file. 
![Uploading IMG_1650.png…]()

**Comment by lin-beta8** [comment]
> > Same question to you: **Which Moodle version are you using?**
> > To all of you, please send us your log files. On iOS, go to iOS Settings, find SEB (in iOS 18 in sub-menu "Apps"), select "Initiate Sending Logs" and return/start SEB. Best is to mail the log file to yourself and then attach it here.
> 
> the moodle version is 4.4.1 and I can’t send log file.

![IMG_1650](https://github.com/user-attachments/assets/215e8649-f646-4db6-91f5-0b97fccf486f)

**Comment by eliassfeir1** [comment]
Dear Dan,

Thank you for your support, we have three instances of Moodle:

1. Moodle 3.10.5+ (Build: 20210716)
2. Moodle 3.10.5 (Build: 20210712)
3. Moodle 3.10.4+ (Build: 20210709)
[SEB-iOS-Client.log](https://github.com/user-attachments/files/17253281/SEB-iOS-Client.log)

Unfortunately, i did not get any overlay notification.
On another note, can you please guide on how to upgrade the SEB for the Moodle versions stated above, for as per your comment, we can still upgrade for Moodle.

Thank you for your support.

[SEB-iOS-Client.log](https://github.com/user-attachments/files/17253281/SEB-iOS-Client.log)

**Comment by danschlet** [comment]
> > > Same question to you: **Which Moodle version are you using?**
> 
> > > To all of you, please send us your log files. On iOS, go to iOS Settings, find SEB (in iOS 18 in sub-menu "Apps"), select "Initiate Sending Logs" and return/start SEB. Best is to mail the log file to yourself and then attach it here.
> 
> > 
> 
> > the moodle version is 4.4.1 and I can’t send log file.
> 
> 
> 
> ![IMG_1650](https://github.com/user-attachments/assets/215e8649-f646-4db6-91f5-0b97fccf486f)
> 
> 

You would need to configure an email account on your iPad, so you could send emails. 

Or can you give me access to some mock/demo exam on your server? You can send the access details to info at safeexambrowser.org.

**Comment by danschlet** [comment]
> Dear Dan,
> 
> Thank you for your support, we have three instances of Moodle:
> 
> 1. Moodle 3.10.5+ (Build: 20210716)
> 2. Moodle 3.10.5 (Build: 20210712)
> 3. Moodle 3.10.4+ (Build: 20210709)
>    [SEB-iOS-Client.log](https://github.com/user-attachments/files/17253281/SEB-iOS-Client.log)
> 
> Unfortunately, i did not get any overlay notification. On another note, can you please guide on how to upgrade the SEB for the Moodle versions stated above, for as per your comment, we can still upgrade for Moodle.
> 
> Thank you for your support.
> 
> [SEB-iOS-Client.log](https://github.com/user-attachments/files/17253281/SEB-iOS-Client.log)

@nexterday What can someone who's running Moodle 3.10.4/5 install to use the moodle-quiz_accessrule_seb_js_api version of the SEB Deeper Integration? Is this still working: https://github.com/ethz-let/moodle-quiz_accessrule_seb_js_api ?

**Comment by nexterday** [comment]
Hi @danschlet & @eliassfeir1 

The https://github.com/ethz-let/moodle-quiz_accessrule_seb_js_api patch should work on the earlier versions, but please proceed with caution as we have not tested it thoroughly, albeit it worked of us on 3.11

**Comment by lin-beta8** [comment]
> > > > Same question to you: **Which Moodle version are you using?**
> > 
> > 
> > > > To all of you, please send us your log files. On iOS, go to iOS Settings, find SEB (in iOS 18 in sub-menu "Apps"), select "Initiate Sending Logs" and return/start SEB. Best is to mail the log file to yourself and then attach it here.
> > 
> > 
> > > 
> > 
> > 
> > > the moodle version is 4.4.1 and I can’t send log file.
> > 
> > 
> > ![IMG_1650](https://private-user-images.githubusercontent.com/183759008/373474789-215e8649-f646-4db6-91f5-0b97fccf486f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNjAxNDgsIm5iZiI6MTcyODA1OTg0OCwicGF0aCI6Ii8xODM3NTkwMDgvMzczNDc0Nzg5LTIxNWU4NjQ5LWY2NDYtNGRiNi05MWY1LTBiOTdmY2NmNDg2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxNjM3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWRmZmI3NDBhNDBlMjhmMzIzYzdhNTI4MDNkNmYwYTkxODkzOGQ1NDYxNzMxMmYwYzQ5NGM5MDgxZTNmNWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aPCFvrpElUmCc8bdnFe38Pw2i3RBwDaLOIIe5oDazuA)
> 
> You would need to configure an email account on your iPad, so you could send emails.
> 
> Or can you give me access to some mock/demo exam on your server? You can send the access details to info at safeexambrowser.org.
2024/10/04 08:26:14:112  DCAppAttestService is available.
2024/10/04 08:26:14:114  DeviceCheck API is supported on the current device.
2024/10/04 08:26:14:116  [SEBCryptor updateEncryptedUserDefaults:1, generateNewSalt:0 newChecksum]
2024/10/04 08:26:14:121  Generated BrowserExamKey salt as there was none defined yet.
2024/10/04 08:26:14:221  Settings changed.
2024/10/04 08:26:14:341  Updated ConfigKey.
2024/10/04 08:26:14:345  Local preferences (client settings) set
2024/10/04 08:26:14:345  SEB was started the first time, UserDefaults were empty.
2024/10/04 08:26:14:612  ---------- INITIALIZING SEB - STARTING SESSION -------------
2024/10/04 08:26:14:614  SEB Version 3.4 (Build 15351)
2024/10/04 08:26:14:614  Bundle ID: org.safeexambrowser.ios.seb, executable: SEB
2024/10/04 08:26:14:614  iPad, running iPadOS 17.7
2024/10/04 08:26:14:614  Device name: iPad
2024/10/04 08:26:14:614  Battery level: 55% (1)
2024/10/04 08:26:14:805  -[AppDelegate applicationDidBecomeActive:]
2024/10/04 08:26:14:910  -[SEBViewController conditionallyStartKioskMode]: allowEditingConfig: 0, initiateResetConfig: 0
2024/10/04 08:26:14:914  -[SEBViewController updateKioskSettingFlags]: secureMode = 0, enableASAM = 1, allowSAM: 0
2024/10/04 08:26:14:914  -[SEBViewController conditionallyStartKioskMode] _enableASAM && !_allowSAM: If AAC/ASAM is enabled and SAM not allowed, we have to check if SAM or Guided Access is already active and deny starting a secured exam until Guided Access is switched off.
2024/10/04 08:26:14:914  -[SEBViewController conditionallyStartKioskMode] Wait at least 2 seconds after app launch
2024/10/04 08:26:14:938  -[SEBViewController assureSAMNotActive]: Single App Mode is not active at least 2 seconds after app launch.
2024/10/04 08:26:14:938  -[SEBViewController conditionallyStartAssessmentMode]
2024/10/04 08:26:14:938  -[SEBViewController conditionallyStartAssessmentMode] Secure mode isn't required in settings (no quit pw), proceed to open start URL
2024/10/04 08:26:14:938  -[SEBViewController startExamWithFallback:]
2024/10/04 08:26:15:158  Default browser user agent string: Mozilla/5.0 (iPad; CPU OS 17_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Version/14.0.3 Safari/605.1.15
2024/10/04 08:26:27:778  -[AppDelegate applicationWillResignActive:]
2024/10/04 08:26:28:926  -[AppDelegate applicationDidBecomeActive:]
2024/10/04 08:26:31:222  -[AppDelegate applicationWillResignActive:]
2024/10/04 08:26:32:507  -[AppDelegate applicationDidEnterBackground:]
2024/10/04 08:26:32:543  -[AppDelegate applicationWillTerminate:]
2024/10/04 08:26:32:545  -[SEBBrowserController init]
2024/10/04 08:26:32:585  -[SEBBrowserController resetBrowser] Cookies, caches and credential stores are being reset when starting new browser session (examSessionClearCookiesOnStart = true)
2024/10/04 10:00:20:087  DCAppAttestService is available.
2024/10/04 10:00:20:088  DeviceCheck API is supported on the current device.
2024/10/04 10:00:20:089  [SEBCryptor updateEncryptedUserDefaults:1, generateNewSalt:0 newChecksum]
2024/10/04 10:00:20:176  Settings changed.
2024/10/04 10:00:20:277  Updated ConfigKey.
2024/10/04 10:00:20:280  Local preferences (client settings) set
2024/10/04 10:00:20:544  -[AppDelegate application:openURL:options:]
2024/10/04 10:00:20:544  URL scheme:sebs
2024/10/04 10:00:20:544  URL query: cmid=67220
2024/10/04 10:00:20:544  URL handling options: {
    UIApplicationOpenURLOptionsOpenInPlaceKey = 0;
}
2024/10/04 10:00:20:544  Get URL event: Loading .seb settings file with URL sebs://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220
2024/10/04 10:00:20:566  ---------- INITIALIZING SEB - STARTING SESSION -------------
2024/10/04 10:00:20:568  SEB Version 3.4 (Build 15351)
2024/10/04 10:00:20:568  Bundle ID: org.safeexambrowser.ios.seb, executable: SEB
2024/10/04 10:00:20:568  iPad, running iPadOS 17.7
2024/10/04 10:00:20:568  Device name: iPad
2024/10/04 10:00:20:568  Battery level: 55% (1)
2024/10/04 10:00:20:569  SEB was started by loading a .seb file/using a seb:// link
2024/10/04 10:00:20:569  closeSettingsBeforeOpeningSEBConfig: callback:<SEBViewController: 0x13e8a7000> selector:saveOrDownloadSEBConfigFromURL:
2024/10/04 10:00:20:570  -[SEBBrowserController init]
2024/10/04 10:00:20:582  [SEBBrowserController openConfigFromSEBURL: sebs://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220]
2024/10/04 10:00:20:582  [SEBBrowserController openConfigFromSEBURL:] Wait until this SEBBrowserController finished initializing and then open this SEB URL.
2024/10/04 10:00:20:738  Created new WKWebViewConfiguration <WKWebViewConfiguration: 0x13df79ed0; processPool = <WKProcessPool: 0x13e0de000; configuration = <_WKProcessPoolConfiguration: 0x300906dc0>>; preferences = <WKPreferences: 0x30123de00>>
2024/10/04 10:00:20:750  -[AppDelegate applicationDidBecomeActive:]
2024/10/04 10:00:21:097  -[SEBBrowserController resetAllCookies] Cookies, caches, credential stores and WKWebsiteDataTypes were reset
2024/10/04 10:00:21:097  -[SEBBrowserController init] Cookies, caches and credential stores have been reset
2024/10/04 10:00:21:097  [SEBBrowserController openConfigFromSEBURL: sebs://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220]
2024/10/04 10:00:21:099  -[SEBBrowserController downloadSEBConfigFileFromURL:originalURL:cookies:sender:] URL: https://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220
2024/10/04 10:00:21:099  Scheme: https, host: contaduria.suayed.fca.unam.mx, resource specifier: //contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220
2024/10/04 10:00:21:208  Default browser user agent string: Mozilla/5.0 (iPad; CPU OS 17_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Version/14.0.3 Safari/605.1.15
2024/10/04 10:00:21:347  URLSession: <__NSURLSessionLocal: 0x13de99270> task: LocalDataTask <15E5AEF1-7A34-49F4-8810-F9EE504FD246>.<1> didReceiveChallenge: <NSURLAuthenticationChallenge: 0x303e19910>
2024/10/04 10:00:21:599  -[SEBBrowserController didDownloadConfigData:response:error:URL:originalURL:] URL: https://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220, error: (null)
2024/10/04 10:00:21:600  NSHTTPURLResponse statusCode: 200
2024/10/04 10:00:21:600  -[SEBBrowserController processDownloadedSEBConfigData:fromURL:originalURL:] URL: https://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220
2024/10/04 10:00:21:610  -[SEBiOSBrowserController openDownloadedSEBConfigData:fromURL:originalURL:] URL: https://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220
2024/10/04 10:00:21:610  Outer prefix of .seb settings file: <nav
2024/10/04 10:00:21:610  -[SEBConfigFileManager storeNewSEBSettings:forEditing:forceConfiguringClient:showReconfiguredAlert:callback:selector:]: {
    NSLocalizedDescription = "Opening Settings Failed";
    NSLocalizedFailureReason = "Loaded data doesn't contain valid SEB settings.";
    NSUnderlyingError = "Error Domain=org.safeexambrowser.SEB Code=11 \"Parsing Settings Failed\" UserInfo={NSLocalizedDescription=Parsing Settings Failed, NSLocalizedFailureReason=No valid prefix and no unencrypted file with valid header}";
} (underlying error: No valid prefix and no unencrypted file with valid header)
2024/10/04 10:00:21:611  -[SEBConfigFileManager storeNewSEBSettingsSuccessful:], continue with callback: <SEBiOSBrowserController: 0x13de31810> selector: storeNewSEBSettingsSuccessful:
2024/10/04 10:00:21:611  Decrypting downloaded SEB config data failed or data needs to be downloaded in a temporary WebView after the user performs web-based authentication.
2024/10/04 10:00:21:611  Trying to download the config in a temporary WebView
2024/10/04 10:00:21:611  [SEBBrowserController openConfigFromSEBURL: https://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220]
2024/10/04 10:00:21:647  Opening modern WebView
2024/10/04 10:00:21:653  WKWebViewConfiguration Optional(<WKWebViewConfiguration: 0x13df79ed0; processPool = <WKProcessPool: 0x13e0de000; configuration = <_WKProcessPoolConfiguration: 0x300906dc0>>; preferences = <WKPreferences: 0x30123de00>>)
2024/10/04 10:00:21:686  -[SEBViewController conditionallyOpenStartExamLockdownWindows:]
2024/10/04 10:00:21:948  webView decidePolicyFor navigationAction: Target frame nil, URL: nil
2024/10/04 10:00:22:458  webView decidePolicyFor navigationAction: Target frame nil, URL: nil
2024/10/04 10:00:22:723  WKWebView didCommit
2024/10/04 10:00:22:723  updateKeyJSVariables: Frame URL nil
2024/10/04 10:00:22:723  updateKeyJSVariables: WebView URL Optional(https://contaduria.suayed.fca.unam.mx/login/index.php)
2024/10/04 10:00:22:723  updateKeyJSVariables: Chosen URL Optional(https://contaduria.suayed.fca.unam.mx/login/index.php)
2024/10/04 10:00:35:131  webView decidePolicyFor navigationAction: Target frame nil, URL: nil
2024/10/04 10:00:35:634  webView decidePolicyFor navigationAction: Target frame nil, URL: nil
2024/10/04 10:00:35:733  webView decidePolicyFor navigationAction: Target frame nil, URL: nil
2024/10/04 10:00:36:000  -[SEBBrowserController downloadSEBConfigFileFromURL:originalURL:cookies:sender:] URL: https://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220
2024/10/04 10:00:36:001  Scheme: https, host: contaduria.suayed.fca.unam.mx, resource specifier: //contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220
2024/10/04 10:00:36:009  -[SEBAbstractWebView sebWebViewDidFailLoadWithError:]: Reported Error 102: Error Domain=WebKitErrorDomain Code=102 "Carga del marco interrumpida" UserInfo={_WKRecoveryAttempterErrorKey=<WKReloadFrameErrorRecoveryAttempter: 0x303d01e60>, NSErrorFailingURLStringKey=https://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220, NSErrorFailingURLKey=https://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220, NSLocalizedDescription=Carga del marco interrumpida}
2024/10/04 10:00:36:140  URLSession: <__NSURLSessionLocal: 0x13f621080> task: LocalDataTask <F7D70A14-EA52-4493-82B2-FE62047D5CBF>.<1> didReceiveChallenge: <NSURLAuthenticationChallenge: 0x303e01b20>
2024/10/04 10:00:36:231  -[SEBBrowserController didDownloadConfigData:response:error:URL:originalURL:] URL: https://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220, error: (null)
2024/10/04 10:00:36:231  NSHTTPURLResponse statusCode: 200
2024/10/04 10:00:36:231  -[SEBBrowserController processDownloadedSEBConfigData:fromURL:originalURL:] URL: https://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220
2024/10/04 10:00:36:231  -[SEBBrowserController processDownloadedSEBConfigData:fromURL:originalURL:] URL: https://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220
2024/10/04 10:00:36:256  -[SEBBrowserTabViewController closeTabWithIndex:]_block_invoke_2: Saving context was successful!
2024/10/04 10:00:36:300  -[SEBiOSBrowserController openDownloadedSEBConfigData:fromURL:originalURL:] URL: https://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220
2024/10/04 10:00:36:300  Outer prefix of .seb settings file: <?xm
2024/10/04 10:00:37:705  -[SEBConfigFileManager storeNewSEBSettingsSuccessful:], continue with callback: <SEBiOSBrowserController: 0x13de31810> selector: storeNewSEBSettingsSuccessful:
2024/10/04 10:00:37:705  Storing downloaded SEB config data was successful
2024/10/04 10:00:37:705  -[SEBViewController storeNewSEBSettingsSuccessful:]: Storing new SEB settings was successful
2024/10/04 10:00:37:705  ---------- RESTARTING SEB SESSION -------------
2024/10/04 10:00:37:736  -[SEBViewController conditionallyStartKioskMode]: allowEditingConfig: 0, initiateResetConfig: 0
2024/10/04 10:00:37:736  -[SEBViewController updateKioskSettingFlags]: secureMode = 0, enableASAM = 1, allowSAM: 0
2024/10/04 10:00:37:737  -[SEBViewController conditionallyStartKioskMode] _enableASAM && !_allowSAM: If AAC/ASAM is enabled and SAM not allowed, we have to check if SAM or Guided Access is already active and deny starting a secured exam until Guided Access is switched off.
2024/10/04 10:00:37:737  -[SEBViewController conditionallyStartKioskMode] Wait at least 2 seconds after app launch
2024/10/04 10:00:37:737  -[SEBViewController assureSAMNotActive]: Single App Mode is not active at least 2 seconds after app launch.
2024/10/04 10:00:37:737  -[SEBViewController conditionallyStartAssessmentMode]
2024/10/04 10:00:37:737  -[SEBViewController conditionallyStartAssessmentMode] Secure mode isn't required in settings (no quit pw), proceed to open start URL
2024/10/04 10:00:37:737  -[SEBViewController startExamWithFallback:]
2024/10/04 10:00:37:741  Opening modern WebView
2024/10/04 10:00:37:741  WKWebViewConfiguration Optional(<WKWebViewConfiguration: 0x13df79ed0; processPool = <WKProcessPool: 0x13e0de000; configuration = <_WKProcessPoolConfiguration: 0x300906dc0>>; preferences = <WKPreferences: 0x30123de00>>)
2024/10/04 10:00:37:749  -[SEBViewController conditionallyOpenStartExamLockdownWindows:]
2024/10/04 10:00:37:857  webView decidePolicyFor navigationAction: Target frame nil, URL: nil
2024/10/04 10:00:38:033  WKWebView didCommit
2024/10/04 10:00:38:033  updateKeyJSVariables: Frame URL nil
2024/10/04 10:00:38:033  updateKeyJSVariables: WebView URL Optional(https://contaduria.suayed.fca.unam.mx/mod/quiz/view.php?id=67220)
2024/10/04 10:00:38:033  updateKeyJSVariables: Chosen URL Optional(https://contaduria.suayed.fca.unam.mx/mod/quiz/view.php?id=67220)
2024/10/04 10:00:38:420  webView decidePolicyFor navigationAction: Target frame nil, URL: nil
2024/10/04 10:00:38:421  closeSettingsBeforeOpeningSEBConfig: callback:<SEBViewController: 0x13e8a7000> selector:saveOrDownloadSEBConfigFromURL:
2024/10/04 10:00:38:446  Navigation action policy for URL sebs://contaduria.suayed.fca.unam.mx/mod/quiz/accessrule/seb/config.php?cmid=67220 was 'cancel'
2024/10/04 10:05:01:986  -[AppDelegate applicationWillResignActive:]
2024/10/04 10:05:02:753  -[AppDelegate applicationDidEnterBackground:]
2024/10/04 10:05:11:333  -[AppDelegate applicationWillEnterForeground:]
2024/10/04 10:05:11:771  -[AppDelegate applicationDidBecomeActive:]
2024/10/04 10:05:11:771  Application returned to active state after it entered background state before. This usually happens when the device is put to sleep.
 Now I cand send los file.

**Comment by eliassfeir1** [comment]
Hi @danschlet  & @nexterday ,

Thank you for your support.
Regarding the patch, we did try to install it and test it with an iPad with the latest update of SEB through Moodle 3.10.5, unfortunately it did not work. 
Can you please provide us with a support email to contact directly, for we are a school that depends on the SEB for our Semester exams. 
Thank you for your continuous support, waiting for your positive feedback.

**Comment by eliassfeir1** [comment]
Hello,

Please note that we tested as well with Moodle[4.0.1+ (Build: 20220512)], with the same issue occurring.

Thank you.

**Comment by danschlet** [comment]
It supposed to work with Moodle 4.1, not 4.0.1.

**Comment by danschlet** [comment]
The Moodle issues in this thread should never have been discussed here, PLEASE ALWAYS OPEN A NEW ISSUE IF IT'S ABOUT ANOTHER PROBLEM. 

I'm closing this, if necessary open a new issue and copy the relevant stuff there.
