### ISSUE TITLE
Browser Window Toolbar

### ISSUE THREAD

**Issue by TomJampen** [SafeExamBrowser/seb-mac#437]
Hi Daniel

We have set "Enable browser window toolbar" to true, but it is not displayed on macOS (Sonoma 14.5), even though "hideBrowserWindowToolbar" is set to false (on option specifically provided for Mac according to the description in the SEB config tool).

Also, the keyboard shortcut mentioned in the SEB config tool (Alt-Cmd-T) and choosing the Menu "Darstellung" -> "Symbolleiste anzeigen" don't not work either.

Is it still possible to see a browser window toolbar?

Kind regards
Tom

**Comment by danschlet** [comment]
Hi Tom

For me the toolbar still works. Did you read the disclaimer regarding full screen mode in the [manual](https://safeexambrowser.org/macosx/mac_usermanual_en.html#AppearancePane): In SEB for macOS the toolbar isn't displayed on the main browser window if this is set to full screen mode.

Daniel

**Comment by TomJampen** [comment]
Hi Daniel

My bad, sorry. I've missed that point. OK, so if we are using fullscreen mode, the only way to get the the menu (for changing zoom) is to use showMenuBar=true. Are there security implications when activating the macOS menu bar?

Tom

**Comment by danschlet** [comment]
Unfortunately the way SEB displays a full screen window isn't compatible to the standard system toolbar and we never had time to implement our own custom toolbar (given that I don't remember ever someone complaining about this limitation, I guess no one uses full screen windows in SEB anymore).  

Most people want to display the menu bar because of the Wi-Fi menu, to be able to re-connect to a Wi-Fi network, if the connection is lost during an exam. SEB terminates any non-system menu bar items, when the user clicks on it. So there are hardly any security implications when displaying the menu bar, unless some menu bar items displays unwanted text without being clicked on.

If you really need zoom with full screen windows, you would need to instruct students which keyboard shortcuts to use.

**Comment by TomJampen** [comment]
Thank you very much for explaining.

Regards
Tom
