### ISSUE TITLE
IOS SEB 2.1.13 (testflight) - no message if the page url is blocked 

### ISSUE THREAD

**Issue by alexandrumarinescu90** [SafeExamBrowser/seb-mac#44]
Tested on test with SEB 2.1.13 (build 11897) for Test Flight on IOS 12.4 with Ipad
Test: https://test.inspera.no/admin#deliver-test/2691009
----------------------------------------------

How to login to test as external: 

URL: test.inspera.no/student 
Username: 2691024
Password: hfrx

invigilator password: a12345
SEB password: b12345

----------------------------------------------

Test steps:
1. Create a question set that has normal and blocked url in resources 
2. Create a normal test with SEB for IOS 
3. As a candidate click on the on the normal url 
4. As a candidate click on the on the blocked url

Results:
 -> Regarding point 3: URL resources opens ok (this is ok)
 -> Regarding point 4: A blank page opens with the title "untitled page". There is no notification that the page is a blocked one.

**Comment by danschlet** [comment]
SEB for iOS shows a "URL blocked" indicator (as an overlay on the top right, which disappears after a moment) for all user-initiated navigation actions. Due to limitations of the UIWebView browser engine, this may not work for navigation action performed using XMLHTTP requests. This may be solved when we will use WKWebView, for UIWebView we cannot solve the issue.
