### ISSUE TITLE
Mac OS 14.6 / Mac 15 Camera issue with SEB 3.4b2 / SEB 3.3

### ISSUE THREAD

**Issue by abhishekdutt-blr** [SafeExamBrowser/seb-mac#444]
**Describe the bug**
In mac Os 14.6 and 15 version, using the SEB 3.3 or SEB 3.4 we are not able to receive the user screen feed, instead it shares my desktop screen feed. Even in earlier versions of 14.5 it was issue but we were able to make it work using the issue link :  https://github.com/SafeExamBrowser/seb-mac/issues/414  (The only way to fix it, is to click on the presenter overlay "small" option and then turning it off, and then it finally shows the SEB). but for 14.6 and 15 there seems no way for us to get it working to show the SEB screen feed. 

**Expected behavior**
In mac os 12/13 and till 14.5, things are working as expected. We are able to launch SEB and run our Assessment platform which has Remote proctoring inbuilt.  It takes User Screen access, and till 14.5 Presenter Overlay support is also working as mentioned in the thread : https://github.com/SafeExamBrowser/seb-mac/issues/414 but from 14.6 and 15 version of Mac, even presenter overlay is not coming and the users desktop is getting visivle

**Screenshots**
![image](https://github.com/user-attachments/assets/74b249a0-55c2-4988-b31d-03073f7fffd7)

**Version Information**
Please complete the following information: 
 - OS: Mac OS 14.6 , Mac OS 15
 - SEB Version : 3.4b2

**Comment by danschlet** [comment]
Apple apparently changed how screen capture in web views works in macOS 14.5. 

SEB has to exempt its windows from screen capture, as otherwise students could just record their exams using system features or additional tools.

As a workaround, you can set allowWindowCapture = true and blockScreenShotsLegacy = true. SEB then uses an older method to block screen shots. I'm not sure though if screen capture in web views works if you disable system screen recordings (allowScreenCapture = false). 

Note that blockScreenShotsLegacy was broken in SEB 3.3.3 and should work again in SEB 3.4 ([please test it with the beta version](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.4b3)).

The best solution would be, if Apple would allow specific applications (like assessment and proctoring applications as SEB) to record everything on the screen, maybe with a new API or special on-demand Entitlements. 

So as only Apple can solve this issue, please create a feedback at https://feedbackassistant.apple.com/
I will do the same, but it's necessary that as many people as possible report this problem to Apple, so that they prioritize it.
