### ISSUE TITLE
SEB v 3.4 for iOS - bundle ID in Identifier field - where is that field?

### ISSUE THREAD

**Issue by ajogrenius** [SafeExamBrowser/seb-mac#448]
**Describe the bug**
I'm struggling with SEB on iOS 18 and can't find the Identifier field where the Bundle ID should be entered.

**Version Information**
Please complete the following information: 
 - OS: iOS 18, Windows 11
 - SEB Version: 3.4 for iOS and 3.7.1 for Windows

![IdentifierField](https://github.com/user-attachments/assets/c36090d2-037f-4859-896c-2d17d78760c0)

**Comment by danschlet** [comment]
In the in-app settings of SEB for iOS you will find the identifier field in the Additional Apps section.

In SEB for Windows or macOS you'll find the Identifier field in SEB Configuration Tool/Setting / Applications/ Permitted Processes.

**Comment by danschlet** [comment]
As stated on the website, the manuals are not all up to date. It's more important to read the release notes, as those provide information about new features.

- SEB configuration files are designed so that one works with ALL versions. 
- BUT we currently don't have the resources to keep all settings/configuration tool interfaces in sync. 
- So you can only rely on the settings editor of the particular platform to provide all the specific settings for that platform version.
- But that is irrelevant for 90% of all users, because you can leave the default value for most settings. SEB in almost any case has the more safe/secure value as default for any setting.
- **VERY IMPORTANT: ONLY CHANGE DEFAULT SETTINGS IF YOU EXACTLY KNOW WHAT THAT SETTING DOES. Otherwise just stick with the default value!**
-  You can just use one configuration file, load it first for example in the SEB Configuration Tool for Windows, change appropriate settings, save the file and load it into the settings editor of SEB for macOS (the latest version, maybe a beta version like SEB 3.4, usually provides also all settings for iOS). Beta versions are always available on GitHub, go to the Releases section of the specific repository.

SEB is freeware. That means Do It Yourself. You need to invest some time to find out how it works and it would be great if people then would contribute tutorials or extensions to the manuals to other SEB users (that's how open source communities usually work).

You can also become contributor to the [SEB Alliance](https://safeexambrowser.org/alliance/fees.html), from the Gold level you get direct consulting from the developers.

**Comment by ajogrenius** [comment]
Hi,
As a matter of fact we are Gold Members but the one and only developer are out of office until Monday Oct 28. So if you could be so very kind and try to help me in their absence.

![image](https://github.com/user-attachments/assets/c1a395a5-09b9-48ae-8008-b8eda79f991f)
