### ISSUE TITLE
The browser automtically closing on Mac OS 10.12

### ISSUE THREAD

**Issue by jasimp** [SafeExamBrowser/seb-mac#68]
The browser automatically closing on Mac OS 10.12
its not asking for the configuration password before that it closing /crashing automatically
is there any compatibility issue with MacAir?

**Comment by danschlet** [comment]
Which version, the latest SEB 2.2.1?

I would need more information: Does your Mac display a crash log afterwards (usually it would)? Please copy the full text and paste it here.

Otherwise I would need the log files from the directory ~/Library/Logs/Safe Exam Browser/.

If there is no clear information in the crash or SEB logs, then I would need access to a configuration which causes SEB to crash, so I could reproduce the issue.

**Comment by jasimp** [comment]
Thank you danschlet for the reply.
Yes, the version is 2.2.1
The issue solved by updating the mac to version 10.14 (Mojave) or 10.15
older version below 10.14 is  not working. The browser opening. but opening with configuration files not success.
I forget to collect the log files as the PC was students PC.

Also another issue i realized that if we re use the same configuration file with access password edit, the password not working!!!
The iOS version has an issue that the exam timer pausing while holding on the screen

**Comment by rsalmei** [comment]
Yeah, unfortunately it doesn't work for me also on 10.12, I'm upgrading now to Catalina 10.15, hope it works.

**Comment by jasimp** [comment]
its working from 10.14 onwards only!

**Comment by danschlet** [comment]
This is not true, SEB 2.2.1 works perfectly for me on macOS 10.13.6, also when opening with configuration files or sebs:// links.

Could anybody of you please post an EXACT description, a video and the SEB log files I asked for above so we could analyze the issue? And best would be a link, test config file or test account so we can try to reproduce it.

If we get imprecise descriptions of problems like "it doesn't start on macOS 10.12", then we cannot do anything if it works with our testing exams and configs.

**Comment by danschlet** [comment]
"The iOS version has an issue that the exam timer pausing while holding on the screen": That might be due to a limitation of the browser engine used by SEB on iOS. I guess the timer skips to the correct time as soon as you stop holding on the screen? If not, then the exam application didn't implement the timer properly (what exam system are you using?).

**Comment by danschlet** [comment]
The is solved in SEB 2.2.2 for macOS: https://safeexambrowser.org/download_en.html#MacOSX

Fixed: Cannot start SEB by opening .seb file on macOS <= 10.12.
