### ISSUE TITLE
allowScreenSharing not consistent

### ISSUE THREAD

**Issue by slartimitvar** [SafeExamBrowser/seb-mac#7]
Using seb2.1.2 on Mac OS 10.12.5
All laptops are fully managed with non-administrative students and have ARD configured but locked from any student access.

We have **allowScreenSharing** set to **true** in the .seb config and in a class of 20 clients around 10 start SEB with the error that screen sharing needs to be turned off before it can start. A reboot will fix most of them but then randomly during the exam SEB will sometimes red screen error about screen sharing and require another reboot.

If we manually turn off screen sharing everything is always ok but this is not feasible as a pre and post safe exam process.

Is the **allowScreenSharing** parameter meant to work in this way or is there something else we should be configuring?

**Comment by danschlet** [comment]
This is not normal, of course SEB should respect the allowScreenSharing setting! As you're mentioning the key name, do you generate the .seb config files yourself? Are you sure the key is set correctly (maybe try it with a file generated with SEB's Preferences editor)? Are you changing the persistent client settings of SEB and/or starting your exams with .seb config files (saved "for starting exams")? 

Otherwise I need to investigate the issue further, can you send me some log file(s) from machines where the error was displayed in the beginning and the red screen appeared during the exam? First set log level to "Debug" in the Security settings tab.

I guess something is strange with your managed MacBooks, as we don't get many reports of false positive screen sharing detection. Or something was changed in the latest macOS 10.12.5 version. SEB is detecting if the ScreensharingAgent process is running or is started during the exam. This is not only triggered by  'Screen Sharing' and 'Remote Management' (can be switched off in System Preferences/Sharing), but also 'Back to My Mac' (iCloud settings) and 'Share Screen' using the Message app.

**Comment by danschlet** [comment]
As GitHub doesn't allow private posts, you can either send the relevant log file(s) by email to info at safeexambrowser.org or in our SourceForge [support forum](https://sourceforge.net/p/seb/support-requests/), where private messages are possible.

Please also send the config file you're using (you can remove passwords and Start URL if you prefer, but don't alter the files otherwise).

**Comment by slartimitvar** [comment]
Thanks for the fast response!

.seb file is generated through normal preferences editor GUI. I just inspected it to confirm there was really a parameter being set and then wrote this issue from there.

I don't have easy direct access to all the student devices but will gather some test machines tomorrow and see if they can replicate the situation.

**Comment by danschlet** [comment]
The problem are bots which scan the Internet for machines with weak VNC passwords. Your network administrators can solve the problem by blocking ports used for VNC in your firewalls/routers.

**Comment by hasqld** [comment]
Nah. Firewall is good.

**Comment by danschlet** [comment]
Well, according to my tests and research the macOS screen sharing daemon doesn't arbitrarily start up (what SEB is detecting), but only when there is an connection attempt to the VNC ports (**you can also see that in the log files of those Macs!**) And in my tests in various networks this didn't happen (just once at some venue I observed it), also not many SEB users have complained about such an issue.

The VNC connection attempts might also come from some machine in the local network, then the firewall would not catch them. Can be one student computer. Might not even be malware, maybe it's some network scanning tool.

If you can't fix it in the network, then can switch the SEB detection off with the allowScreenSharing = false setting. Unfortunately I can't do much more in SEB code than detecting that macOS started the screen sharing daemon. But I filed an enhancement request to Apple for a better kiosk mode which would prevent screen sharing by default.
