### ISSUE TITLE
Safe exam browser

### ISSUE THREAD

**Issue by Habibq8** [SafeExamBrowser/seb-mac#76]
I accidentally opened the program and I did not have a test to take, and now I have to enter a password to exit the program.

can u help me with that and I don't have school or college right now, also I'm using MacBook 
![a5fb6472-490f-4c80-a4ad-7ff1df0dfbf0](https://user-images.githubusercontent.com/76058857/102237753-0ae3ff80-3f06-11eb-813c-496ec010eef3.jpg)

**Comment by danschlet** [comment]
In general, you have to ask your exam organizer for that password. 

You can also tell them that they set up SEB poorly for that exam: They should hide the link to the SEB exam configuration or use an exam (settings) password in that config file, which they would communicate just before the exam, so that students couldn't accidentally open the application with a configuration which has a quit password set.

Otherwise you can follow the first FAQ for SEB macOS [here](https://safeexambrowser.org/faq/faq_en.html#MacOSX):  Restart your Mac and use the terminal command.
