### ISSUE TITLE
Not able to force close SEB on macOS

### ISSUE THREAD

**Issue by nervenfacharzt** [SafeExamBrowser/seb-mac#97]
Hello, 

somehow I seem to have kept open an instance of SEB now for months after having done an examen and now by incident opened it which causes to show a red screen right after every startup of my macbook asking for a password to close the SEB.

Now the problem is since that is months ago I don´t know the password any more. How would I force close the SEB in order to be able to use my macbook again?

Thx for your help.

Best regards,
Al

**Comment by danschlet** [comment]
Hi,

I'm sorry that you did encounter this issue. In general, the organizer of that exam should have been able to tell you the SEB quit password for that exam, so you could quit SEB correctly. That's why we suggest to always first contact the organizers of an exam if you encounter any problems.

But there is of course another way how you can use your MacBook again, it is mentioned in the [FAQ section](https://safeexambrowser.org/faq/faq_en.html#MacOSX) on our website (also see below). In short you have to start/restart your Mac while holding the Shift key (this is called safe mode). Then you can delete the Safe Exam Browser application or reset its settings (see below).

**What to do if SEB doesn't react anymore/cannot be quit?**
Did you try the keyboard shortcut Cmd-Q? If SEB asks for the Quit Password, you need to ask your exam support for it (see first paragraph of this page). If SEB really cannot be quit, you need to force restart or force shutdown your Mac:
1. Try to press the Touch ID button (that's the power button on current Macs, other models might still have a dedicated power button) for 6 seconds, your Mac will switch off then. 
2. Wait a minute or two and press the power button again, your Mac will boot up again. 
3. SEB should not be started automatically. Proceed to step 5. If SEB is started automatically and you still cannot quit it, then proceed to step 4.
4. Again press the power button for 6 seconds to turn off your Mac, wait a minute, press the power button again and immediately press and hold the Shift key as your Mac starts up (this is called safe mode).
5. Open the Terminal app (you can use the Spotlight search icon on the upper right in your menu bar to find Terminal).
6. Type/copy paste this text: `defaults delete org.safeexambrowser.Safe-Exam-Browser`. This deletes the client configuration of the Safe Exam Browser application, so when starting it is showing the same information page like when it was installed first
7. You can do your exam again, make sure your Mac is fully charged or use a power adapter.
SEB cannot "damage" your computer, software or documents. But with a force restart, you can loose unsaved changes to documents or in the worst case the file system on a hard drive/SSD needs to be repaired by some third-party software. Always save all documents you work on before starting SEB and ideally quit applications with open documents. As always when working with any computer and any software, regularly make backups of your documents and system.


Hope this helps. Otherwise please let us know again.

**Comment by nervenfacharzt** [comment]
Hello,

thx for your tip. I had to do another mode to get into the safe mode as I use a macbook air with apple a1 cpu... but when being there defaults delete org.safeexambrowser.Safe-Exam-Browser gives "Domain (org.sageexambrowser.safe-Exam-Browser) not found. Defaults have not been changed."

So how would I disable Safe Exam Browser?

Best regards,

Al

**Comment by danschlet** [comment]
That was a mistake on my side, since SEB 2.2, the correct command is:

`defaults delete org.safeexambrowser.SafeExamBrowser`
